//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientHospitalApp.ServiceReferenceDAOLayer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patient", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Patient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_PatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        private System.DateTime DOBField;
        
        private int SSNField;
        
        private int ID_GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientHospitalApp.ServiceReferenceDAOLayer.ArrayOfInt relativeListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientHospitalApp.ServiceReferenceDAOLayer.ArrayOfInt orderOfPatientListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Patient {
            get {
                return this.ID_PatientField;
            }
            set {
                if ((this.ID_PatientField.Equals(value) != true)) {
                    this.ID_PatientField = value;
                    this.RaisePropertyChanged("ID_Patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int SSN {
            get {
                return this.SSNField;
            }
            set {
                if ((this.SSNField.Equals(value) != true)) {
                    this.SSNField = value;
                    this.RaisePropertyChanged("SSN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int ID_Gender {
            get {
                return this.ID_GenderField;
            }
            set {
                if ((this.ID_GenderField.Equals(value) != true)) {
                    this.ID_GenderField = value;
                    this.RaisePropertyChanged("ID_Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ClientHospitalApp.ServiceReferenceDAOLayer.ArrayOfInt relativeList {
            get {
                return this.relativeListField;
            }
            set {
                if ((object.ReferenceEquals(this.relativeListField, value) != true)) {
                    this.relativeListField = value;
                    this.RaisePropertyChanged("relativeList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public ClientHospitalApp.ServiceReferenceDAOLayer.ArrayOfInt orderOfPatientList {
            get {
                return this.orderOfPatientListField;
            }
            set {
                if ((object.ReferenceEquals(this.orderOfPatientListField, value) != true)) {
                    this.orderOfPatientListField = value;
                    this.RaisePropertyChanged("orderOfPatientList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderOfPatient", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderOfPatient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_OrderField;
        
        private System.DateTime DateOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SymptomsField;
        
        private int ID_PatientField;
        
        private int ID_DoctorField;
        
        private int ID_OrderStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientHospitalApp.ServiceReferenceDAOLayer.ArrayOfInt specimentsInOrderListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Order {
            get {
                return this.ID_OrderField;
            }
            set {
                if ((this.ID_OrderField.Equals(value) != true)) {
                    this.ID_OrderField = value;
                    this.RaisePropertyChanged("ID_Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime DateOrder {
            get {
                return this.DateOrderField;
            }
            set {
                if ((this.DateOrderField.Equals(value) != true)) {
                    this.DateOrderField = value;
                    this.RaisePropertyChanged("DateOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Symptoms {
            get {
                return this.SymptomsField;
            }
            set {
                if ((object.ReferenceEquals(this.SymptomsField, value) != true)) {
                    this.SymptomsField = value;
                    this.RaisePropertyChanged("Symptoms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ID_Patient {
            get {
                return this.ID_PatientField;
            }
            set {
                if ((this.ID_PatientField.Equals(value) != true)) {
                    this.ID_PatientField = value;
                    this.RaisePropertyChanged("ID_Patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int ID_Doctor {
            get {
                return this.ID_DoctorField;
            }
            set {
                if ((this.ID_DoctorField.Equals(value) != true)) {
                    this.ID_DoctorField = value;
                    this.RaisePropertyChanged("ID_Doctor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int ID_OrderStatus {
            get {
                return this.ID_OrderStatusField;
            }
            set {
                if ((this.ID_OrderStatusField.Equals(value) != true)) {
                    this.ID_OrderStatusField = value;
                    this.RaisePropertyChanged("ID_OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ClientHospitalApp.ServiceReferenceDAOLayer.ArrayOfInt specimentsInOrderList {
            get {
                return this.specimentsInOrderListField;
            }
            set {
                if ((object.ReferenceEquals(this.specimentsInOrderListField, value) != true)) {
                    this.specimentsInOrderListField = value;
                    this.RaisePropertyChanged("specimentsInOrderList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SpecimentsInOrder", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SpecimentsInOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_SpecimentOrderField;
        
        private int ID_OrderField;
        
        private int ID_SpecimentField;
        
        private int ID_SpecimentStatusField;
        
        private System.DateTime DateOfTakingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NurseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientHospitalApp.ServiceReferenceDAOLayer.ArrayOfInt testsInOrderListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_SpecimentOrder {
            get {
                return this.ID_SpecimentOrderField;
            }
            set {
                if ((this.ID_SpecimentOrderField.Equals(value) != true)) {
                    this.ID_SpecimentOrderField = value;
                    this.RaisePropertyChanged("ID_SpecimentOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ID_Order {
            get {
                return this.ID_OrderField;
            }
            set {
                if ((this.ID_OrderField.Equals(value) != true)) {
                    this.ID_OrderField = value;
                    this.RaisePropertyChanged("ID_Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ID_Speciment {
            get {
                return this.ID_SpecimentField;
            }
            set {
                if ((this.ID_SpecimentField.Equals(value) != true)) {
                    this.ID_SpecimentField = value;
                    this.RaisePropertyChanged("ID_Speciment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ID_SpecimentStatus {
            get {
                return this.ID_SpecimentStatusField;
            }
            set {
                if ((this.ID_SpecimentStatusField.Equals(value) != true)) {
                    this.ID_SpecimentStatusField = value;
                    this.RaisePropertyChanged("ID_SpecimentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DateOfTaking {
            get {
                return this.DateOfTakingField;
            }
            set {
                if ((this.DateOfTakingField.Equals(value) != true)) {
                    this.DateOfTakingField = value;
                    this.RaisePropertyChanged("DateOfTaking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Nurse {
            get {
                return this.NurseField;
            }
            set {
                if ((object.ReferenceEquals(this.NurseField, value) != true)) {
                    this.NurseField = value;
                    this.RaisePropertyChanged("Nurse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ClientHospitalApp.ServiceReferenceDAOLayer.ArrayOfInt testsInOrderList {
            get {
                return this.testsInOrderListField;
            }
            set {
                if ((object.ReferenceEquals(this.testsInOrderListField, value) != true)) {
                    this.testsInOrderListField = value;
                    this.RaisePropertyChanged("testsInOrderList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDAOLayer.WebServiceHospitalSoap")]
    public interface WebServiceHospitalSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldResponse HelloWorld(ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldResponse> HelloWorldAsync(ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetDataPatientResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataPatient", ReplyAction="*")]
        ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientResponse GetDataPatient(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataPatient", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientResponse> GetDataPatientAsync(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientRequest request);
        
        // CODEGEN: Generating message contract since element name GetDataOrderResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataOrder", ReplyAction="*")]
        ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderResponse GetDataOrder(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderResponse> GetDataOrderAsync(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderRequest request);
        
        // CODEGEN: Generating message contract since element name GetDataSpecimentResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataSpeciment", ReplyAction="*")]
        ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentResponse GetDataSpeciment(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataSpeciment", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentResponse> GetDataSpecimentAsync(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataPatientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataPatient", Namespace="http://tempuri.org/", Order=0)]
        public ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientRequestBody Body;
        
        public GetDataPatientRequest() {
        }
        
        public GetDataPatientRequest(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataPatientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IdPatient;
        
        public GetDataPatientRequestBody() {
        }
        
        public GetDataPatientRequestBody(int IdPatient) {
            this.IdPatient = IdPatient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataPatientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataPatientResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientResponseBody Body;
        
        public GetDataPatientResponse() {
        }
        
        public GetDataPatientResponse(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataPatientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientHospitalApp.ServiceReferenceDAOLayer.Patient GetDataPatientResult;
        
        public GetDataPatientResponseBody() {
        }
        
        public GetDataPatientResponseBody(ClientHospitalApp.ServiceReferenceDAOLayer.Patient GetDataPatientResult) {
            this.GetDataPatientResult = GetDataPatientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataOrder", Namespace="http://tempuri.org/", Order=0)]
        public ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderRequestBody Body;
        
        public GetDataOrderRequest() {
        }
        
        public GetDataOrderRequest(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDataOrderRequestBody {
        
        public GetDataOrderRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderResponseBody Body;
        
        public GetDataOrderResponse() {
        }
        
        public GetDataOrderResponse(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientHospitalApp.ServiceReferenceDAOLayer.OrderOfPatient GetDataOrderResult;
        
        public GetDataOrderResponseBody() {
        }
        
        public GetDataOrderResponseBody(ClientHospitalApp.ServiceReferenceDAOLayer.OrderOfPatient GetDataOrderResult) {
            this.GetDataOrderResult = GetDataOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataSpecimentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataSpeciment", Namespace="http://tempuri.org/", Order=0)]
        public ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentRequestBody Body;
        
        public GetDataSpecimentRequest() {
        }
        
        public GetDataSpecimentRequest(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDataSpecimentRequestBody {
        
        public GetDataSpecimentRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataSpecimentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataSpecimentResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentResponseBody Body;
        
        public GetDataSpecimentResponse() {
        }
        
        public GetDataSpecimentResponse(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataSpecimentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientHospitalApp.ServiceReferenceDAOLayer.SpecimentsInOrder GetDataSpecimentResult;
        
        public GetDataSpecimentResponseBody() {
        }
        
        public GetDataSpecimentResponseBody(ClientHospitalApp.ServiceReferenceDAOLayer.SpecimentsInOrder GetDataSpecimentResult) {
            this.GetDataSpecimentResult = GetDataSpecimentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceHospitalSoapChannel : ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceHospitalSoapClient : System.ServiceModel.ClientBase<ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap>, ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap {
        
        public WebServiceHospitalSoapClient() {
        }
        
        public WebServiceHospitalSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceHospitalSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceHospitalSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceHospitalSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldResponse ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap.HelloWorld(ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldRequest inValue = new ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldRequest();
            inValue.Body = new ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldRequestBody();
            ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldResponse retVal = ((ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldResponse> ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap.HelloWorldAsync(ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldResponse> HelloWorldAsync() {
            ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldRequest inValue = new ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldRequest();
            inValue.Body = new ClientHospitalApp.ServiceReferenceDAOLayer.HelloWorldRequestBody();
            return ((ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientResponse ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap.GetDataPatient(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientRequest request) {
            return base.Channel.GetDataPatient(request);
        }
        
        public ClientHospitalApp.ServiceReferenceDAOLayer.Patient GetDataPatient(int IdPatient) {
            ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientRequest inValue = new ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientRequest();
            inValue.Body = new ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientRequestBody();
            inValue.Body.IdPatient = IdPatient;
            ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientResponse retVal = ((ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap)(this)).GetDataPatient(inValue);
            return retVal.Body.GetDataPatientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientResponse> ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap.GetDataPatientAsync(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientRequest request) {
            return base.Channel.GetDataPatientAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientResponse> GetDataPatientAsync(int IdPatient) {
            ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientRequest inValue = new ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientRequest();
            inValue.Body = new ClientHospitalApp.ServiceReferenceDAOLayer.GetDataPatientRequestBody();
            inValue.Body.IdPatient = IdPatient;
            return ((ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap)(this)).GetDataPatientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderResponse ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap.GetDataOrder(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderRequest request) {
            return base.Channel.GetDataOrder(request);
        }
        
        public ClientHospitalApp.ServiceReferenceDAOLayer.OrderOfPatient GetDataOrder() {
            ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderRequest inValue = new ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderRequest();
            inValue.Body = new ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderRequestBody();
            ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderResponse retVal = ((ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap)(this)).GetDataOrder(inValue);
            return retVal.Body.GetDataOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderResponse> ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap.GetDataOrderAsync(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderRequest request) {
            return base.Channel.GetDataOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderResponse> GetDataOrderAsync() {
            ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderRequest inValue = new ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderRequest();
            inValue.Body = new ClientHospitalApp.ServiceReferenceDAOLayer.GetDataOrderRequestBody();
            return ((ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap)(this)).GetDataOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentResponse ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap.GetDataSpeciment(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentRequest request) {
            return base.Channel.GetDataSpeciment(request);
        }
        
        public ClientHospitalApp.ServiceReferenceDAOLayer.SpecimentsInOrder GetDataSpeciment() {
            ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentRequest inValue = new ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentRequest();
            inValue.Body = new ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentRequestBody();
            ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentResponse retVal = ((ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap)(this)).GetDataSpeciment(inValue);
            return retVal.Body.GetDataSpecimentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentResponse> ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap.GetDataSpecimentAsync(ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentRequest request) {
            return base.Channel.GetDataSpecimentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentResponse> GetDataSpecimentAsync() {
            ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentRequest inValue = new ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentRequest();
            inValue.Body = new ClientHospitalApp.ServiceReferenceDAOLayer.GetDataSpecimentRequestBody();
            return ((ClientHospitalApp.ServiceReferenceDAOLayer.WebServiceHospitalSoap)(this)).GetDataSpecimentAsync(inValue);
        }
    }
}
